sonar.projectKey=csv-manager
sonar.projectName=Gestor de Documentos CSV
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/tests

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/uploads/**,**/*.test.ts
sonar.typescript.tsconfigPaths=backend/tsconfig.json,frontend/tsconfig.json

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.javascript.file.suffixes=.js,.jsx,.cjs,.mjs
sonar.typescript.file.suffixes=.ts,.tsx,.vue
